### ISSUE TITLE
How do I disable the "Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them" output when running docker build?

### ISSUE THREAD

**Issue by ryan-blunden** [docker/scan-cli-plugin#149]
I want to prevent the "Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them" output when running `docker build` in Docker for Desktop on macOS but can't find a way to do that.

Running version 3.3.1 (63152).

**Comment by thaJeztah** [comment]
You can disable these messages by setting the `DOCKER_SCAN_SUGGEST=false` environment variable (see https://github.com/docker/compose-cli/pull/1475);

In your current shell;

```bash
export DOCKER_SCAN_SUGGEST=false
```

Or

```bash
DOCKER_SCAN_SUGGEST=false docker build <....>
```

To set that variable automatically, you can add it to your `~/.bash_profile` or `~/.bashrc` (if you're using Bash as shell) or `~/.zprofile` or `~/.zshrc` if you're using `zsh` as shell.

**Comment by glours** [comment]
@ryan-blunden can we close the issue?

**Comment by f355** [comment]
is it possible to stop printing this banner to stdout when `-q` option is provided? breaks a lot of automation, you know.

**Comment by thaJeztah** [comment]
@f355 that was reported in https://github.com/docker/compose-cli/issues/1517, and should already be fixed through https://github.com/docker/compose-cli/pull/1532, which looks to be in version `v1.0.13` of the "Cloud integration" cli, which should be included with an upcoming release of Docker Desktop (currently it's shipping 1.0.12);

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
```

>  breaks a lot of automation, you know.

Curious; are you running automation on top of Docker Desktop? (Docker Desktop is more targeted at interactive use; I don't think the message is currently included in Linux packages)

**Comment by f355** [comment]
@thaJeztah oh, great news, thank you!

as to automation - well, we have tests that use docker images built from our source tree, basically much more involved variations of:
```
IMAGE=$(docker build -q .)
docker run $IMAGE
```
...and all of them broke.

**Comment by f355** [comment]
> Docker Desktop is more targeted at interactive use

@thaJeztah if you forgive me a little out-of-place rant, I think this statement is complete bollocks. people use Docker Desktop in non-interactive mode all the time - to run tests, to build images to be deployed to production using scripts and so on - like, what do you do if you're a startup with macs and don't have a CI server yet? you write bash scripts. there is a certain level of unsigned API contract that the community expects to be held, and frustration ensues when it gets broken.

that API contract is not limited at CLI, of course. at our company, we had to stick to Docker Desktop 2.2.0.5 for the past year. why? because SCTP protocol support got silently dropped after that version, in an effort to reduce the VM image size as I understand. there was an issue created: https://github.com/docker/for-mac/issues/4552, but it received zero attention from anybody at Docker Inc and got auto-closed. now it seems that SCTP is back - again, silently, we discovered it pretty much by accident. I understand that there's probably a dozen companies in the world that need SCTP on docker, but it's not limited to that protocol - it's the general attitude that matters, I mean, how hard is it to make a list of kernel modules that you removed from the linuxkit image and stick it in the changelog? I guess it's important to mention that SCTP is not available on macOS and Docker is the only option to work with SCTP without resorting to full-blown virtual machines on VirtualBox/Parallels and writing your own tooling around them.

all that said, Docker Desktop remains the only sensible way to work with containers on non-linux systems, and I'd very much appreciate less breakages in the future.

**Comment by f355** [comment]
the same goes for `docker-compose` being replaced by `docker compose`. how hard is it to make the old command print a warning and still do what it's supposed to do instead of printing an error and exiting?

**Comment by f355** [comment]
now after upgrade docker compose broke down. if you specify `ports: "8080"`, it doesn't map the ephemeral port on the host anymore - you have to either specify the host port explixitly or use the extended yaml syntax. this is beyond ridiculous, guys, I'm at a loss of words.

**Comment by thaJeztah** [comment]
> there is a certain level of unsigned API contract that the community expects to be held, and frustration ensues when it gets broken.

The CLI output / output format is not an official API (this is what the API is for), and not guaranteed to be "stable" (as in: output format can change); that said the `--quiet` case was a bug, and that's being fixed.

> that API contract is not limited at CLI, of course. at our company, we had to stick to Docker Desktop 2.2.0.5 for the past year. why? because SCTP protocol support got silently dropped after that version, in an effort to reduce the VM image size as I understand

I'm not familiar with the background on that change and wether it was only for space consideration or (e.g.) for compatiblity issues with specific kernel versions. I agree that if this was a deliberate decision, such changes _should_ be included in release notes, which may have been missed.

> how hard is it to make the old command print a warning and still do what it's supposed to do instead of printing an error and exiting?

Could you describe the issue you're seeing? I tried running `docker-compose`, and although it prints an extra line at the end of the "usage" output, it still works;

```
Docker Compose is now in the Docker CLI, try `docker compose`
```

At some point, Docker Desktop will stop shipping the python implementation in the default installation; likely an alias will be provided at that point (but allowing you to manually install the python version if needed).

> now after upgrade docker compose broke down. if you specify ports: - "8080", it doesn't map the ephemeral port on the host anymore - you have to either specify the host port explicitly or use the extended yaml syntax. this is beyond ridiculous, guys, I'm at a loss of words.

Trying to reproduce this with both `docker compose` and `docker-compose`;

```yaml
services:
  web:
    image: nginx:alpine
    ports:
      - "80"
```

```bash
docker compose up -d
docker compose port web 80
0.0.0.0:61447

curl -s localhost:61447 | grep 'Welcome'
<title>Welcome to nginx!</title>
<h1>Welcome to nginx!</h1>

docker compose down -v
```

```bash
docker-compose up -d
docker-compose port web 80
0.0.0.0:61613

curl -s localhost:61613 | grep 'Welcome'
<title>Welcome to nginx!</title>
<h1>Welcome to nginx!</h1>
```

I'm not able to reproduce the issue, but if you have details, can you please open a separate ticket instead?

**Comment by thaJeztah** [comment]
I'm closing this ticket, because the original question was answered, and the related `--quiet` bug was fixed (but may still have to be shipped).

Please open separate tickets for other bugs, as reporting unrelated issues makes it really hard to keep track.
