### ISSUE TITLE
Automatically accept Snyk license

### ISSUE THREAD

**Issue by mcandre** [docker/scan-cli-plugin#169]
Could the Snyk license please be included in the Docker EULA? We can make the command line interface more seamless, so that users don't have to bother with annoying prompts or special flags as late as running the `docker scan` command. This is the kind of thing that can be clarified at the time the Docker software package installs.

**Comment by glours** [comment]
@thaJeztah is right, there is legal agreements between Docker and Snyk, that's why users should explicitly accept Snyk License.
For CI or scripting purposes, you can use the `--accept-license` as we did for [our e2e tests for example](https://github.com/docker/scan-cli-plugin/blob/ce161dd124f4ce61e5e610e351af4c2fb11c272a/e2e/scan_test.go#L60)

**Comment by thaJeztah** [comment]
Thanks @glours!

Looks like the question was answered, so let me go ahead and close this one, but feel free to continue the conversation
